"""Generate the SPICE runner presets: netlists, ngspice results computed here, and the model's
prediction for the same operating point.

The web build cannot run ngspice, so it shows these stored results for the unmodified presets.
The desktop app re-runs any (guarded) netlist live through the sandboxed ngspice command.

    python scripts/make_spice_presets.py          # needs ngspice on PATH
Writes data/spice_presets.json and docs/js/data/spice_presets.js.
"""
from __future__ import annotations

import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from watt_forge import spice
from watt_forge.flagship import model, sim
from watt_forge.flagship.params import Params

ROOT = Path(__file__).resolve().parents[1]
P = Params()

RC = """* RC low-pass sanity check: 12 V step into 1 kohm / 1 uF
VIN in 0 DC 12
R1 in out 1k
C1 out 0 1u
.tran 1u 10m
.meas tran vavg AVG v(out) FROM=9m TO=10m
.end
"""


def flagship(vin: float, frac: float, label: str):
    pout = frac * P.spec.p_rated(vin)
    a = model.best(vin, 48.0, pout, P)
    s = sim.ideal_switch_efficiency(vin, 48.0, pout, a["fs"], a["mode"], P, a["phase"])
    ckt = s["res"]["ckt"]
    net = spice.flagship_netlist(vin, 48.0, a["mode"], s["d1"], s["d2"], s["phase"], a["fs"], ckt.r_sw,
                                 ckt.dcr + P.r_pcb, P.l, ckt.c1, ckt.c2, ckt.esr, s["x0"])
    return {
        "id": f"flagship_{a['mode']}_{int(vin)}V",
        "label": label,
        "netlist": net,
        "about": (f"Flagship power stage, {a['mode']} mode, {vin:g} V panel to 48 V, {pout:.0f} W, "
                  f"{a['fs']/1e3:.0f} kHz. Ideal switches with R_ds(on), zero dead time: conduction losses only, "
                  "so efficiency here is higher than the full model, which adds switching, core and housekeeping losses."),
        "expect": {"conduction_only_eta": s["eta"], "full_model_eta": a["eta"], "pout_W": pout},
        "derive": "eta",
    }


def presets():
    out = [
        {"id": "rc", "label": "RC sanity check (1 kohm, 1 uF)", "netlist": RC,
         "about": "Smallest possible netlist: the output settles to the 12 V input. Use it to check ngspice works.",
         "expect": {"vavg": 12.0}, "derive": None},
        {"id": "sync_buck", "label": "Synchronous buck, 12 V to ~6 V (worked example)",
         "netlist": spice.buck_netlist(12.0, 0.5, 200e3, 15e-6, 200e-6, 1.0, 0.010, 0.020, periods=1500, meas_periods=50),
         "about": "Lesson-2 worked example: D = 0.5, R_on = 10 mohm, DCR = 20 mohm, 1 ohm load. "
                  "Ratio with losses: Vout = D*Vin*R/(R + R_on + DCR) = 5.825 V.",
         "expect": {"vout": 0.5 * 12.0 * 1.0 / (1.0 + 0.010 + 0.020)}, "derive": None},
        flagship(56.0, 1.0, "Flagship, buck mode: 56 V panel, full power"),
        flagship(24.0, 1.0, "Flagship, boost mode at the 1:2 sweet spot: 24 V panel"),
        flagship(48.0, 1.0, "Flagship, buck-boost mode: 48 V panel"),
    ]
    return out


def ngspice_version() -> str:
    cp = subprocess.run(["ngspice", "-v"], capture_output=True, text=True)
    m = re.search(r"ngspice-(\d+)", cp.stdout + cp.stderr)
    return f"ngspice-{m.group(1)}" if m else "ngspice"


def main():
    if not shutil.which("ngspice"):
        raise SystemExit("ngspice is not installed: sudo apt-get install ngspice")
    items = []
    for p in presets():
        spice.check_netlist(p["netlist"])  # presets must pass the same guard users face
        res = spice.run(p["netlist"], timeout_s=600)
        if res.get("_returncode") != 0:
            raise SystemExit(f"{p['id']}: ngspice failed")
        meas = {k: v for k, v in res.items() if not k.startswith("_")}
        if p.pop("derive") == "eta":
            meas["eta"] = meas["pout"] / meas["pin"]
        p["result"] = {k: round(v, 9) for k, v in sorted(meas.items())}
        items.append(p)
        print(f"{p['id']:28s} {p['result']}")
    doc = {"_about": "Generated by scripts/make_spice_presets.py. 'result' is what ngspice measured when the "
                     "repository was built; 'expect' is the analytic or model value for the same circuit.",
           "simulator": ngspice_version(), "presets": items}
    (ROOT / "data" / "spice_presets.json").write_text(json.dumps(doc, indent=1) + "\n")
    js = ("// AUTO-GENERATED by scripts/make_spice_presets.py -- do not edit.\n"
          f"export const SPICE_PRESETS = {json.dumps(doc, indent=1)};\n")
    (ROOT / "docs" / "js" / "data" / "spice_presets.js").write_text(js)


if __name__ == "__main__":
    main()
