"""Generate the control-library data: converter efficiency table, MPPT benchmark (all profiles x
all trackers x 3 noise seeds), efficiency-control map, daily energy waterfall, and the parity
fixture the JavaScript test checks against.

    python scripts/make_control_data.py            # ~10 minutes on two cores
    python scripts/make_control_data.py --quick    # reuse data/eta_table.json and the benchmark

Writes data/{eta_table,control_benchmark,control_traces,control_efficiency}.json,
docs/js/data/{eta_table,control_benchmark,control_efficiency}.js, tests/fixtures/control_parity.json.
"""
from __future__ import annotations

import argparse
import json
import sys
from multiprocessing import Pool
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from watt_forge import pv  # noqa: E402
from watt_forge.control import bench, efficiency as E, mppt as M, profiles as PR  # noqa: E402

SEEDS = (7, 8, 9)
TRACE_EVERY = 25          # ticks: 2 Hz traces for the README charts
DATA = ROOT / "data"
JS = ROOT / "docs" / "js" / "data"
_CACHE = {}


def _shared():
    if not _CACHE:
        panel = pv.Panel()
        _CACHE.update(panel=panel, oracle=bench.MppOracle(panel), eta=bench.EtaTable())
    return _CACHE["panel"], _CACHE["oracle"], _CACHE["eta"]


def _job(args):
    profile, key, seed = args
    panel, oracle, eta = _shared()
    rec = TRACE_EVERY if seed == SEEDS[0] else 0
    r = bench.run(M.make(key), PR.get(profile), seed=seed, oracle=oracle, eta=eta, panel=panel, record_every=rec)
    return profile, key, seed, r


def write_js(name: str, const: str, doc) -> None:
    (JS / f"{name}.js").write_text(f"// AUTO-GENERATED by scripts/make_control_data.py -- do not edit.\n"
                                   f"export const {const} = {json.dumps(doc, indent=1)};\n")


def mppt_benchmark():
    jobs = [(p, k, s) for p in PR.PROFILES for k in M.keys() for s in SEEDS]
    with Pool(2) as pool:
        results = pool.map(_job, jobs)
    res, traces = {}, {}
    for profile, key, seed, r in results:
        res.setdefault(profile, {}).setdefault(key, []).append(r)
        if "trace" in r:
            traces.setdefault(profile, {"t": r["trace"]["t"], "pmpp": r["trace"]["pmpp"]})
            traces[profile][key] = {"p": r["trace"]["p"], "v": r["trace"]["v"]}
    table = {}
    for profile, per in res.items():
        table[profile] = {}
        for key, runs in per.items():
            em = [x["eta_mppt"] for x in runs]
            es = [x["eta_sys"] for x in runs]
            table[profile][key] = {
                "eta_mppt": round(sum(em) / len(em), 6), "eta_mppt_min": round(min(em), 6), "eta_mppt_max": round(max(em), 6),
                "eta_sys": round(sum(es) / len(es), 6), "e_lost_J": round(sum(x["e_lost_J"] for x in runs) / len(runs), 2),
                "e_mpp_J": round(runs[0]["e_mpp_J"], 2), "seconds": runs[0]["seconds"]}
    # overall: energy-weighted across the five profiles
    overall = {}
    for key in M.keys():
        e_mpp = sum(table[p][key]["e_mpp_J"] for p in table)
        lost = sum(table[p][key]["e_lost_J"] for p in table)
        sys_e = sum(table[p][key]["eta_sys"] * table[p][key]["e_mpp_J"] for p in table)
        overall[key] = {"eta_mppt": round(1 - lost / e_mpp, 6), "eta_sys": round(sys_e / e_mpp, 6)}
    doc = {
        "_about": "Dynamic MPPT efficiency (EN 50530 definition) of every tracker on every profile, mean of "
                  f"{len(SEEDS)} noise seeds (min/max given). eta_sys includes the flagship conversion losses. "
                  "Generated by scripts/make_control_data.py; parameters from data/mppt_tuned.json.",
        "seeds": list(SEEDS), "dt": PR.DT,
        "plant": {"alpha": bench.ALPHA, "sigma_v": bench.SIGMA_V, "sigma_i": bench.SIGMA_I, "lsb_v": bench.LSB_V, "lsb_i": bench.LSB_I},
        "profiles": {k: v[0] for k, v in PR.PROFILES.items()},
        "algorithms": {k: {"name": M.ALGORITHMS[k].name, "family": M.FAMILY[k], "ref": M.REFERENCE[k]} for k in M.keys()},
        "params": {k: M.make(k).params() for k in M.keys()},
        "results": table, "overall": overall,
    }
    return doc, traces


def efficiency_map():
    vins = [16.0, 24.0, 32.0, 40.0, 48.0, 56.0]
    loads = [0.025, 0.05, 0.1, 0.2, 0.4, 0.75, 1.0]
    from watt_forge.flagship.params import Params
    p = Params()
    rows = []
    for vin in vins:
        for f in loads:
            pout = f * p.spec.p_rated(vin) if hasattr(p.spec, "p_rated") else f * min(p.spec.p_max, 0.97 * p.spec.iin_max * vin)
            kappa = E.kappa_estimate(vin, pout)
            op = E.operating_point(vin, 48.0, pout, kappa, p)
            rows.append({"vin": vin, "load": f, "pout": round(pout, 3), "loss": {k: round(v, 5) for k, v in op["loss"].items()},
                         "fs": {k: op["fs"][k] for k in ("fixed", "online", "optimum", "hit_rate")},
                         "td_ns": {k: round(op["td"][k] * 1e9, 3) for k in ("fixed", "online", "optimum")},
                         "td_hit_rate": op["td"]["hit_rate"], "sigma_W": round(op["sigma"], 5),
                         "burst": {k: op["burst"][k] for k in ("p_burst", "f_burst", "dv_pp") if k in op["burst"]}})
    return {"vins": vins, "loads": loads, "rows": rows}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--quick", action="store_true", help="reuse the efficiency table and the benchmark")
    a = ap.parse_args()
    if not a.quick:
        doc = bench.build_eta_table()
        (DATA / "eta_table.json").write_text(json.dumps(doc) + "\n")
        bdoc, traces = mppt_benchmark()
        (DATA / "control_benchmark.json").write_text(json.dumps(bdoc, indent=1) + "\n")
        (DATA / "control_traces.json").write_text(json.dumps(traces) + "\n")
    eta_doc = json.loads((DATA / "eta_table.json").read_text())
    bdoc = json.loads((DATA / "control_benchmark.json").read_text())
    # labels and names come from the code, so a --quick run picks up wording changes
    bdoc["profiles"] = {k: v[0] for k, v in PR.PROFILES.items()}
    for k in M.keys():
        bdoc["algorithms"][k].update({"name": M.ALGORITHMS[k].name, "family": M.FAMILY[k], "ref": M.REFERENCE[k]})
    (DATA / "control_benchmark.json").write_text(json.dumps(bdoc, indent=1) + "\n")
    write_js("eta_table", "ETA_TABLE", eta_doc)
    write_js("control_benchmark", "CONTROL_BENCHMARK", bdoc)

    # efficiency controls: map + daily energy (flagship tracker = global scan, EN 50530 average)
    en = [bdoc["results"][p]["scan"]["eta_mppt"] for p in ("en50530_high", "en50530_low")]
    eta_scan = sum(en) / len(en)
    day = E.daily_energy(eta_scan)
    per_algo = {}
    for key in M.keys():
        e = [bdoc["results"][p][key]["eta_mppt"] for p in ("en50530_high", "en50530_low")]
        per_algo[key] = round(day["energy_Wh"]["available"] * sum(e) / len(e), 3)
    edoc = {"_about": "Efficiency controls on the flagship loss model (watt_forge/control/efficiency.py). "
                      "Losses in W, energies in Wh. Model predictions, not measurements.",
            "constants": {"fixed_fs": E.FIXED_FS, "td_grid_ns": [round(t * 1e9, 3) for t in E.TD_GRID],
                          "burst_powers": list(E.BURST_POWERS), "burst_freqs": list(E.BURST_FREQS),
                          "burst_min_cycles": E.BURST_MIN_CYCLES, "burst_max_ripple": E.BURST_MAX_RIPPLE, "e_wake": E.E_WAKE,
                          "avg_samples": E.AVG_SAMPLES, "mc_seeds": E.MC_SEEDS,
                          "sigma_sample": [E.SIGMA_V_SAMPLE, E.SIGMA_I_SAMPLE]},
            "map": efficiency_map(),
            "day": {"energy_Wh": {k: round(v, 3) for k, v in day["energy_Wh"].items()}, "eta_mppt": round(eta_scan, 6),
                    "vout": day["vout"], "step_min": day["step_min"],
                    "rows": [{k: (round(v, 4) if isinstance(v, float) else v) for k, v in r.items()} for r in day["rows"]],
                    "after_mppt_by_algorithm_Wh": per_algo}}
    (DATA / "control_efficiency.json").write_text(json.dumps(edoc, indent=1) + "\n")
    write_js("control_efficiency", "CONTROL_EFFICIENCY", edoc)

    # parity fixture for tests/js/control.mjs
    short = PR.get("shading")[:1500] + PR.get("clouds")[:1500]
    panel, oracle, eta = _shared()
    fx = {"mppt": {}, "ops": []}
    for key in M.keys():
        r = bench.run(M.make(key), short, seed=11, oracle=oracle, eta=eta, panel=panel, record_every=50)
        fx["mppt"][key] = {"params": M.make(key).params(), "eta_mppt": r["eta_mppt"], "eta_sys": r["eta_sys"],
                           "p": r["trace"]["p"], "v": r["trace"]["v"]}
    for vin, pout, kappa in ((36.0, 300.0, 1.2), (35.8, 20.0, 0.38), (56.0, 400.0, 3.7), (24.0, 200.0, 2.0), (48.0, 300.0, 3.0)):
        op = E.operating_point(vin, 48.0, pout, kappa)
        fx["ops"].append({"args": [vin, 48.0, pout, kappa], "loss": op["loss"], "fs_path": op["fs"]["path"],
                          "td_path": op["td"]["path"], "fs_finals": op["fs"]["finals"], "td_finals": op["td"]["finals"],
                          "f_burst": op["burst"].get("f_burst")})
    (ROOT / "tests" / "fixtures" / "control_parity.json").write_text(json.dumps(fx) + "\n")
    print("control data written; overall:", {k: v["eta_mppt"] for k, v in bdoc["overall"].items()})


if __name__ == "__main__":
    main()
