"""Generate web data modules, docs/REFERENCES.md, and the JS-parity fixtures from the
canonical Python sources.

    python scripts/make_web_data.py
"""
from __future__ import annotations

import json
import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from watt_forge import losses, magnetics, pv, ratios, switched_cap as sc, topologies  # noqa: E402
from watt_forge.flagship import control as C, model  # noqa: E402
from watt_forge.flagship.params import Params  # noqa: E402

JSDATA = ROOT / "docs" / "js" / "data"
FIX = ROOT / "tests" / "fixtures"


def js_module(name: str, obj) -> str:
    return f"// AUTO-GENERATED by scripts/make_web_data.py from data/*.json -- do not edit.\nexport const {name} = {json.dumps(obj, indent=1)};\n"


def references_md(refs: dict) -> str:
    out = ["# References and verified figures", "",
           f"_Last verified: {refs['last_verified']}. Generated from `data/references.json` by `scripts/make_web_data.py`; edit the JSON, not this file._",
           "",
           "**Rule used everywhere in this repo:** every efficiency figure is quoted with its exact test conditions (input, output, power) and what it includes. A best-case lab number is never presented as typical. Research-stage results are labelled as such.",
           "",
           "## Corrections to commonly quoted numbers",
           "",
           "- The MDPI *Sustainability* 2024 hybrid SC buck-boost paper's 96 % / 99.2 % are **PV energy-harvest ratios**, not converter efficiency.",
           "- A \"96-97 % switched-capacitor buck-boost for PV\" could **not** be verified; the closest verified paper (Liang et al., APEC 2012) reports 92.5 %.",
           "- The CoBB (monolithic bidirectional GaN buck-boost) results are from **MIT** (Aron, Eliat-Eliat, Buonato, Coday) and **exclude gate-drive loss**.",
           "- The TI GaN optimizer's 99.5-99.6 % is a **pass-through** state; its switching peak is 99.0 %.",
           "- The piezoelectric \">99 %\" figure (Boles et al. 2021) appears to be **calculated**, not measured.",
           ""]
    cats = []
    for r in refs["references"]:
        if r["category"] not in cats:
            cats.append(r["category"])
    for cat in cats:
        out += [f"## {cat}", ""]
        for r in refs["references"]:
            if r["category"] != cat:
                continue
            link = f"https://doi.org/{r['doi']}" if r.get("doi") else r["url"]
            yr = f" ({r['year']})" if r.get("year") else ""
            out.append(f"### {r['title']}")
            out.append("")
            out.append(f"- **Authors:** {r['authors']}{yr}. **Venue:** {r['venue']}.")
            out.append(f"- **Link:** [{r['doi'] or r['url']}]({link})" + (f" (also {r['url']})" if r.get("doi") and r["url"] != link else ""))
            if r.get("headline"):
                out.append(f"- **Headline figure:** {r['headline']}")
            if r.get("conditions"):
                out.append(f"- **Exact conditions:** {r['conditions']}")
            out.append(f"- **In plain language:** {r['summary']}")
            out.append(f"- **Verification:** {r['status']}")
            out.append("")
    out += ["## Component data", "",
            "Device parameters live in `data/devices.json`; each entry lists which fields were checked against the manufacturer datasheet (`verified`) and explains every estimate (`notes`). The flagship bill of materials, with a status column, is `hardware/flagship/BOM.csv`.", "",
            "## Open-source tools used or referenced", "",
            "| Tool | Use here | License note |", "|---|---|---|",
            "| [ngspice](https://ngspice.sourceforge.io) | desktop simulation back end; cross-checks the Python circuit simulation | BSD-3 style; invoked as an external program, not bundled |",
            "| [KiCad](https://gitlab.com/kicad/code/kicad) | schematic / BOM conventions for the reference design | GPL-3; conventions only, no code copied |",
            "| [Apache ECharts](https://github.com/apache/echarts), [plotly.js](https://github.com/plotly/plotly.js) | considered for charts; the site ships its own small SVG charts instead so it can run under a strict CSP with zero third-party scripts | Apache-2 / MIT |",
            "| IEEE TPEL / APEC / COMPEL papers | every topology and loss reference above, cited by DOI | publisher copyright; cited, never reproduced |",
            ""]
    return "\n".join(out)


def parity_fixtures() -> dict:
    fx = {"core": [], "topologies": [], "flagship": [], "pv": [], "control": None}
    core = fx["core"]
    for d in (0.1, 0.25, 0.5, 0.8):
        core.append(["mBoost", [d], ratios.m_boost(d)])
        core.append(["mBuckBoost", [d], ratios.m_buck_boost(d)])
        core.append(["mBoostLossy", [d, 10.0, 0.02, 0.03], ratios.m_boost_lossy(d, 10.0, 0.02, 0.03)])
        core.append(["mBuckBoostLossy", [d, 5.0, 0.01, 0.02], ratios.m_buck_boost_lossy(d, 5.0, 0.01, 0.02)])
        for top in ("buck", "boost", "buck_boost"):
            core.append(["kCrit", [top, d], ratios.k_crit(top, d)])
            core.append(["mDcm", [top, d, 5e-6, 10.0, 100e3], ratios.m_dcm(top, d, 5e-6, 10.0, 100e3)])
    core.append(["qossAt", [90e-9, 50.0, 28.0, 0.653], losses.qoss_at(90e-9, 50.0, 28.0, 0.653)])
    core.append(["eossFromQoss", [60e-9, 28.0, 0.653], losses.eoss_from_qoss(60e-9, 28.0, 0.653)])
    core.append(["zvsResidualFraction", [6.0, 10e-9, 60e-9], losses.zvs_residual_fraction(6.0, 10e-9, 60e-9)])
    core.append(["overlap", [48.0, 10.0, 10e-9, 10e-9, 200e3], losses.overlap(48, 10, 10e-9, 10e-9, 200e3)])
    mat = magnetics.MATERIALS["ferrite_generic"]
    k = magnetics.steinmetz_k(mat)
    core.append(["igseKi", [k, mat["alpha"], mat["beta"]], magnetics.igse_ki(k, mat["alpha"], mat["beta"])])
    for d in (0.2, 0.5, 0.7):
        core.append(["igseTriangular", [k, mat["alpha"], mat["beta"], 100e3, 0.05, d], magnetics.igse_triangular(k, mat["alpha"], mat["beta"], 100e3, 0.05, d)])
    for f in (1e4, 1e5, 1e6):
        core.append(["simulateSeriesParallel.r_out", [48.0, 23.5, 10e-6, 0.01, f], sc.simulate_series_parallel(48, 23.5, 10e-6, 0.01, f)["r_out"]])
        core.append(["rOut", [[0.5], [10e-6], f, [0.5] * 4, [0.01] * 4], sc.r_out([0.5], [10e-6], f, [0.5] * 4, [0.01] * 4)])
    cases = [dict(topology="buck", vin=48, vout=12, pout=100), dict(topology="boost", vin=24, vout=48, pout=200, device="EPC2361"),
             dict(topology="buck_boost", vin=48, vout=24, pout=60, sync=False), dict(topology="sepic", vin=24, vout=36, pout=50),
             dict(topology="cuk", vin=24, vout=36, pout=50, device="ISC030N10NM6"), dict(topology="flyback", vin=48, vout=12, pout=30, n=0.5),
             dict(topology="four_switch", vin=48, vout=24, pout=150), dict(topology="four_switch", vin=24, vout=48, pout=150),
             dict(topology="four_switch", vin=48, vout=48, pout=150, fs=100e3), dict(topology="buck", vin=12, vout=3.3, pout=20, ripple_frac=2.5)]
    for c in cases:
        r = topologies.design(**c)
        fx["topologies"].append([c, {"eta": r["eta"], "total_loss": r["total_loss"], "l": r["l"], "d": r["d"], "losses": r["losses"]}])
    p = Params()
    for vin, frac, mode, fs in ((56.0, 1.0, "buck", 75e3), (24.0, 0.8, "boost", 100e3), (48.0, 0.5, "buckboost", 50e3),
                                (36.0, 0.2, "boost", 150e3), (60.0, 0.1, "buck", 300e3), (47.0, 1.0, "buckboost", 75e3)):
        pout = frac * p.spec.p_rated(vin)
        r = model.evaluate(vin, 48.0, pout, fs, mode, p)
        fx["flagship"].append({"kind": "evaluate", "args": [vin, 48.0, pout, fs, mode],
                               "out": {k: r[k] for k in ("eta", "d1", "d2", "il", "ripple_pp", "cfly_ripple", "n_hard", "phase")} | {"losses": r["losses"]}})
    for vin, frac in ((12.0, 1.0), (30.0, 0.3), (50.0, 0.75)):
        pout = frac * p.spec.p_rated(vin)
        r = model.best(vin, 48.0, pout, p)
        fx["flagship"].append({"kind": "best", "args": [vin, 48.0, pout], "out": {"eta": r["eta"], "fs": r["fs"], "mode": r["mode"]}})
    panel = pv.Panel()
    for irr, t in (([1000.0] * 3, 25.0), ([800.0, 800.0, 200.0], 45.0)):
        fx["pv"].append({"irr": irr, "t": t, "mpp": pv.global_mpp(irr, t, panel),
                         "i_at": [[v, pv.panel_current(v, irr, t, panel)] for v in (5.0, 20.0, 35.0, 42.0, 48.0)]})
    # controller: a scripted (open-loop) measurement trace; outputs must match line-for-line
    ctrl = C.Ctrl()
    trace = []
    for kk in range(1400):
        vin = 49.0 if kk < 1060 else 30.0 + 8.0 * math.sin(kk / 37.0)
        iin = 0.0 if kk < 1060 else 9.0 - 0.1 * (vin - 30.0)
        vout = 48.0 + (10.0 if 1300 <= kk < 1310 else 0.0)
        m = C.Meas(vin=vin, iin=iin, vout=vout)
        o = ctrl.step_once(m)
        trace.append([[vin, iin, vout, 0.0, 40.0], o.line()])
    fx["control"] = trace
    return fx


def main():
    JSDATA.mkdir(parents=True, exist_ok=True)
    FIX.mkdir(parents=True, exist_ok=True)
    devs = json.loads((ROOT / "data" / "devices.json").read_text())["devices"]
    (JSDATA / "devices.js").write_text(js_module("DEVICES", devs))
    lut = json.loads((ROOT / "data" / "fs_lut.json").read_text())
    (JSDATA / "fs_lut.js").write_text(js_module("FS_LUT", lut))
    refs = json.loads((ROOT / "data" / "references.json").read_text())
    (JSDATA / "references.js").write_text(js_module("REFERENCES", refs))
    (ROOT / "docs" / "REFERENCES.md").write_text(references_md(refs))
    import csv
    with open(ROOT / "hardware" / "flagship" / "BOM.csv", newline="") as f:
        bom = list(csv.DictReader(f))
    (JSDATA / "bom.js").write_text(js_module("BOM", bom))
    (FIX / "parity.json").write_text(json.dumps(parity_fixtures()))
    print("web data, REFERENCES.md and parity fixtures written")


if __name__ == "__main__":
    main()
