"""Design-space exploration for the flagship: device selection, frequency schedule,
efficiency curves, weighted efficiency, device-technology comparison, and the
controller's frequency lookup table. Writes data/*.json (consumed by the web app,
the README figures and the C controller header generator).

Run:  python -m watt_forge.flagship.design
"""
from __future__ import annotations

import json
from dataclasses import replace
from pathlib import Path
from typing import Dict, List

from .. import efficiency
from . import model
from .params import Params

ROOT = Path(__file__).resolve().parents[2]
DATA = ROOT / "data"
WEB_DATA = ROOT / "docs" / "data"

VINS = [12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 47, 48, 49, 50, 52, 54, 56, 58, 60]
LOADS = [0.05, 0.10, 0.20, 0.30, 0.50, 0.75, 1.00]
M_EDGES = [0.6, 0.8, 0.9, 0.97, 1.03, 1.2, 1.5, 1.8, 1.95, 2.05, 2.3, 3.0, 5.0]
P_EDGES = [0.0, 0.15, 0.35, 0.65, 1.01]
GAN_CANDIDATES = ["EPC2361", "EPC2302", "EPC2071", "EPC2088", "EPC2218", "EPC2619"]
TECH_COMPARE = ["EPC2361", "ISC030N10NM6", "CSD19536KTT", "IMT65R010M2H", "C3M0015065K"]


def _pt(r: Dict) -> Dict:
    keep = ("vin", "vout", "pout", "fs", "mode", "label", "d1", "d2", "phase", "il", "iin", "ripple_pp",
            "i_peak", "cfly_ripple", "n_hard", "loss_stage", "loss_total", "eta_stage", "eta", "feasible")
    d = {k: r.get(k) for k in keep}
    d["losses"] = {k: round(v, 5) for k, v in r["losses"].items()}
    d["violations"] = r.get("violations", [])
    return d


def curves(p: Params, vout: float = 48.0) -> Dict:
    out = {}
    for frac in LOADS:
        out[str(frac)] = [_pt(model.best(v, vout, frac * p.spec.p_rated(v), p)) for v in VINS]
    return out


def weighted_vs_vin(p: Params, vout: float = 48.0) -> List[Dict]:
    res = []
    for v in VINS:
        cache: Dict[float, float] = {}

        def eta_at(frac, v=v):
            if frac not in cache:
                cache[frac] = model.best(v, vout, frac * p.spec.p_rated(v), p)["eta"]
            return cache[frac]
        res.append({"vin": v, "cec": efficiency.cec(eta_at), "euro": efficiency.euro(eta_at)})
    return res


def device_sweep(p: Params, ids: List[str], points=((56, 1.0), (36, 0.75), (24, 0.5), (48, 0.3), (18, 0.3))) -> Dict:
    """CEC-style weighted efficiency at three input voltages plus a few spot points per device."""
    out = {}
    for dev in ids:
        q = replace(p, switch=dev)
        spots = []
        for vin, frac in points:
            r = model.best(vin, 48.0, frac * q.spec.p_rated(vin), q)
            spots.append({"vin": vin, "frac": frac, "eta": r["eta"], "fs": r["fs"], "loss": r["loss_total"],
                          "losses": {k: round(v, 5) for k, v in r["losses"].items()}})
        cecs = []
        for vin in (24.0, 36.0, 56.0):
            cecs.append(efficiency.cec(lambda f, vin=vin: model.best(vin, 48.0, f * q.spec.p_rated(vin), q)["eta"]))
        out[dev] = {"spots": spots, "cec_avg": sum(cecs) / 3.0, "cec_by_vin": dict(zip(("24", "36", "56"), cecs))}
    return out


def tech_compare(p: Params) -> Dict:
    """Si vs GaN vs SiC in the SAME design, at a fixed switching frequency so the
    comparison isolates the device (each also shown at its own best frequency)."""
    out = {}
    for dev in TECH_COMPARE:
        q = replace(p, switch=dev)
        rows = []
        for vin in (24.0, 36.0, 56.0):
            fixed = model.evaluate(vin, 48.0, 0.75 * q.spec.p_rated(vin), 150e3,
                                   "buck" if vin > 48 else "boost", q)
            bestp = model.best(vin, 48.0, 0.75 * q.spec.p_rated(vin), q)
            rows.append({"vin": vin, "eta_150k": fixed["eta"], "loss_150k": fixed["loss_total"],
                         "losses_150k": {k: round(v, 5) for k, v in fixed["losses"].items()},
                         "eta_best": bestp["eta"], "fs_best": bestp["fs"]})
        from .. import devices
        d = devices.get(dev)
        # hottest switch estimate at 150 kHz, 56 V, 75 % load: switching + conduction of one device
        out[dev] = {"tech": d.tech, "vds": d.vds, "rows": rows}
    return out


def fs_lut(p: Params) -> Dict:
    tab = []
    for i in range(len(M_EDGES) - 1):
        m_mid = 0.5 * (M_EDGES[i] + M_EDGES[i + 1]) if i < len(M_EDGES) - 2 else 4.0
        vin = min(max(48.0 / m_mid, p.spec.vin_min), p.spec.vin_max)
        row = []
        for j in range(len(P_EDGES) - 1):
            frac = 0.5 * (P_EDGES[j] + min(P_EDGES[j + 1], 1.0))
            r = model.best(vin, 48.0, frac * p.spec.p_rated(vin), p)
            row.append(r["fs"])
        tab.append(row)
    return {"m_edges": M_EDGES, "p_edges": P_EDGES, "fs_hz": tab, "p_max": p.spec.p_max,
            "note": "generated by watt_forge.flagship.design from the analytic loss model"}


def c_header(lut: Dict) -> str:
    rows = ",\n".join("    {" + ", ".join(f"{v:.1f}" for v in r) + "}" for r in lut["fs_hz"])
    return (
        "/* AUTO-GENERATED by watt_forge.flagship.design -- do not edit. REFERENCE ONLY. */\n"
        "#ifndef WF_FS_LUT_H\n#define WF_FS_LUT_H\n"
        f"#define WF_LUT_NM {len(lut['m_edges'])}\n#define WF_LUT_NP {len(lut['p_edges'])}\n"
        f"#define WF_LUT_PMAX {lut['p_max']:.1f}\n"
        "static const double WF_LUT_M_EDGES[WF_LUT_NM] = {" + ", ".join(repr(float(x)) for x in lut["m_edges"]) + "};\n"
        "static const double WF_LUT_P_EDGES[WF_LUT_NP] = {" + ", ".join(repr(float(x)) for x in lut["p_edges"]) + "};\n"
        "static const double WF_LUT_FS[WF_LUT_NM - 1][WF_LUT_NP - 1] = {\n" + rows + "\n};\n#endif\n"
    )


def build(write: bool = True) -> Dict:
    p = Params()
    res = {
        "params": p.to_dict(),
        "vins": VINS,
        "loads": LOADS,
        "curves": curves(p),
        "weighted": weighted_vs_vin(p),
        "bypass_48": _pt(model.bypass(48.0, 400.0, p)),
        "device_sweep": device_sweep(p, GAN_CANDIDATES),
        "tech_compare": tech_compare(p),
        "nominal": {
            "buck_56V_400W": _pt(model.best(56.0, 48.0, 400.0, p)),
            "boost_36V_300W": _pt(model.best(36.0, 48.0, 300.0, p)),
            "sc_24V_300W": _pt(model.best(24.0, 48.0, 300.0, p)),
            "boost_12V_rated": _pt(model.best(12.0, 48.0, p.spec.p_rated(12.0), p)),
        },
    }
    lut = fs_lut(p)
    if write:
        DATA.mkdir(exist_ok=True)
        WEB_DATA.mkdir(parents=True, exist_ok=True)
        (DATA / "flagship_results.json").write_text(json.dumps(res, indent=1))
        (WEB_DATA / "flagship_results.json").write_text(json.dumps(res))
        (DATA / "fs_lut.json").write_text(json.dumps(lut, indent=1))
        (WEB_DATA / "fs_lut.json").write_text(json.dumps(lut))
        (ROOT / "hardware" / "flagship" / "control" / "wf_fs_lut.h").write_text(c_header(lut))
    return res


if __name__ == "__main__":
    r = build()
    best_eta = max(pt["eta"] for c in r["curves"].values() for pt in c)
    print("peak predicted efficiency (system, incl. housekeeping): %.4f" % best_eta)
    for w in r["weighted"]:
        if w["vin"] in (12, 24, 36, 48, 56, 60):
            print("Vin %4.0f V  CEC %.4f  Euro %.4f" % (w["vin"], w["cec"], w["euro"]))
    for dev, d in r["device_sweep"].items():
        print("%-10s CEC avg %.4f" % (dev, d["cec_avg"]))
